### ISSUE TITLE
Infografia.Bautista.Garcia.Maria.Lizbeth

### ISSUE THREAD

**Issue by BautistaLizbeth** [SistemasTecTlaxiaco/infografia-BautistaLizbeth#2]
[infografia.Maria.Lizbeth.Bautista.Garcia.pdf](https://github.com/user-attachments/files/16788459/infografia.Maria.Lizbeth.Bautista.Garcia.pdf)

**Comment by LenninGS-0** [comment]
Redacción y Ortografía:14/14
Exposición de ideas Centrales:16/16
Organización de ideas centrales:14/14
Uso de Imágenes y Colores:14/14
Presentación Visual:13/14
Referencias:13/14
Presentación:14/14
Calificación Final: 19.6/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
